baseurl: /
title: Blog.Yahya
theme: github.com/adityatelange/hugo-PaperMod

build:
  processing:
    skip_processing: true

ignoreErrors: "error-remote-getjson"


params: # each blog post
  ShowBreadCrumbs: true
  ShowToc: true
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  #email: yahya.ayman9@gmail.com
  opengraph: true
  #shareTwitter: true
  dateFormat: 'Mon, Jan 2, 2006'
  Author: Yahya Korayem
  
  # home-info mode
  homeInfoParams:
    Title: "\U0001F44B \U0001F47E \U0001F4BB"
    Content: My learning and tinkering journey
  socialIcons: # optional
        - name: Github
          url: "https://github.com/dievoom-png"
        - name: Linkedin
          url: "https://www.linkedin.com/in/yahya-ayman-8a27961b4/"
  
  assets:
    favicon: "favicons/favicon.ico"

profileMode:
        enabled: false
        title: "\U0001F44B \U0001F47E \U0001F4BB"
        subtitle: "This is subtitle"

socialIcons: # optional
        - name: Github
          url: "https://github.com/dievoom-png"
        - name: LinkedIn
          url: "https://www.linkedin.com/in/yahya-ayman-8a27961b4/"



  
Permalinks:
  post: '/:filename/'
  tags: /:title/
  categories: /:title/
  archvies: /archives/

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
  - identifier: categories
    name: Categories
    url: /categories/
    weight: 10

  - identifier: tags
    name: Tags
    url: /tags/
    weight: 20
    
  - identifier: archives
    name: Archives
    url: /archives/
    weight: 30
